//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using PanHG.ViewModel;
namespace PanHG {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class HGSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HGSettings defaultInstance = ((HGSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HGSettings())));
        
        public static HGSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\HG")] // This is default path for your Local Repository, you can change it.
        public string LocalRepo {
            get {
                return ((string)(this["LocalRepo"]));
            }
            set {
                this["LocalRepo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\HG")]  // This is default path for your Clone Repository, you can change it.
        public string CloneRepo {
            get {
                return ((string)(this["CloneRepo"]));
            }
            set {
                this["CloneRepo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ObservableCollection<CheckBoxRepos> CloneRepoList
        {
            get {
                return ((ObservableCollection<CheckBoxRepos>)(this["CloneRepoList"]));
            }
            set {
                this["CloneRepoList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ObservableCollection<CheckBoxRepos> UpdateRepoList
        {
            get {
                return ((ObservableCollection<CheckBoxRepos>)(this["UpdateRepoList"]));
            }
            set {
                this["UpdateRepoList"] = value;
            }
        }
    }
}
